services:
  ubuntu20_shenlanxueyuan_cw2_container:
    image: adamliu1/shenlanxueyuan_cw2_rl:latest
    container_name: ubuntu20_shenlanxueyuan_cw2_container
    ulimits:
      nofile:
        soft: 524288
        hard: 524288
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /g1_cw2_ws
    # Enabling Nvidia GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Environment variables passed to the container
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - XAUTHORITY=/tmp/.docker.xauth
      # for hybrid graphics
      # - "__NV_PRIME_RENDER_OFFLOAD=1"
      # - "__GLX_VENDOR_LIBRARY_NAME=nvidia"
      # - "NVIDIA_VISIBLE_DEVICES=all"
      # - "NVIDIA_DRIVER_CAPABILITIES=all"
    # This mounts the host directories into the container 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb:rw
      - ../:/g1_cw2_ws:rw
    entrypoint: /bin/bash
